### ISSUE TITLE
Unable to compile for M0 Mainboard

### ISSUE THREAD

**Issue by tomsyco** [DFRobot/DFRobotDuinoBoard#6]
Receiving the error below. 

Arduino: 1.8.5 (Windows 7), Board: "DFRduino M0 MainBoard"

WARNING: Category '' in library EEPROM is not valid. Setting to 'Uncategorized'
Warning: platform.txt from core 'DFRobot Boards' contains deprecated recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} "{build.path}/{archive_file}" "{object_file}", automatically converted to recipe.ar.pattern="{compiler.path}{compiler.ar.cmd}" {compiler.ar.flags} "{archive_file_path}" "{object_file}". Consider upgrading this core.
arm-none-eabi-g++: error: C:\Users\a1024349\AppData\Local\Temp\arduino_build_968536/core/syscalls.c.o: No such file or directory

exit status 1
Error compiling for board DFRduino M0 MainBoard.

This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.

**Comment by tomsyco** [comment]
Code compiles fine for other boards.

**Comment by ExploitSage** [comment]
I am unsure what the root cause is, but it appears it might be a bad cached core lingering around from the installation. Try this as a workaround: Go to `File>Preferences`, and un-check the `Aggressively cache compiled core` option. Then Compile/Unload your Sketch. If all is successful, please also try re-checking the `Aggressively cache compiled core` option and compiling again, if it still works, it gives further validity to my hypothesis.

**Comment by tomsyco** [comment]
This fixed it. Thanks
